pipeline{
    agent any
      tools{
        nodejs "NodeJS"
        }
    stages{
        stage('Cleanup before Install'){
            steps{
                sh 'rm -rf TSINextReactApp'
            }
        }
        stage ('Setup'){
            steps{
            sh 'npm install'
            }
        stage ('Build')
        steps{
        git clone: 'main', 'https://github.com/Tizzer1331/TSINextReactApp.git'
            }
        }
    }
}